apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: talenthub-logging-agent

spec:
  selector:
    matchLabels:
      app: talenthub-logging-agent

  template:
    metadata:
      labels:
        app: talenthub-logging-agent

    spec:
      containers:
        - name: logging-agent
          image: busybox:1.36
          command:
            - sh
            - -c
            - while true; do echo "Collecting TalentHub logs..."; sleep 30; done
